# Generated by Django 3.2.13 on 2024-02-13 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry_table',
            name='date_field',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
