# Generated by Django 3.2.13 on 2024-03-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_dropdownoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry_table',
            name='dropdown',
            field=models.CharField(default=-19800, max_length=100),
        ),
    ]
