# Generated by Django 3.2.13 on 2025-04-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_enquiry_table_dropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry_table',
            name='education',
            field=models.CharField(default=-19800, max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry_table',
            name='skills',
            field=models.CharField(default=-19800, max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry_table',
            name='dropdown',
            field=models.CharField(max_length=100),
        ),
    ]
