# Generated by Django 3.2.13 on 2025-04-27 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20250423_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_work_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('requirement', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
                ('date_field', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
