# Generated by Django 3.2.13 on 2025-04-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_company_work_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_work_details',
            old_name='name',
            new_name='company_name',
        ),
    ]
