# Generated by Django 5.1.7 on 2025-05-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_contactmessage_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry_table',
            name='date_field',
        ),
        migrations.RemoveField(
            model_name='enquiry_table',
            name='dropdown',
        ),
        migrations.RemoveField(
            model_name='enquiry_table',
            name='education',
        ),
        migrations.RemoveField(
            model_name='enquiry_table',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='enquiry_table',
            name='skills',
        ),
        migrations.AddField(
            model_name='enquiry_table',
            name='subject',
            field=models.CharField(default='No Subject', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry_table',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enquiry_table',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
